// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBooksZhanr.DBContext;

#nullable disable

namespace WebBooksZhanr.Migrations
{
    [DbContext(typeof(BooksZhanrDB))]
    partial class BooksZhanrDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiBib.Model.Books", b =>
                {
                    b.Property<int>("Id_Book")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Book"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Zhanr")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Year_Izd")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Book");

                    b.HasIndex("Id_Zhanr");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("WebApiBib.Model.Zhanr", b =>
                {
                    b.Property<int>("Id_Zhanr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Zhanr"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Zhanr");

                    b.ToTable("Zhanr");
                });

            modelBuilder.Entity("WebApiBib.Model.Books", b =>
                {
                    b.HasOne("WebApiBib.Model.Zhanr", "Zhanr")
                        .WithMany()
                        .HasForeignKey("Id_Zhanr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zhanr");
                });
#pragma warning restore 612, 618
        }
    }
}
